//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninponix_Office.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI Light, 12pt")]
        public global::System.Drawing.Font textdoc_Font {
            get {
                return ((global::System.Drawing.Font)(this["textdoc_Font"]));
            }
            set {
                this["textdoc_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color textdoc_fontcolor {
            get {
                return ((global::System.Drawing.Color)(this["textdoc_fontcolor"]));
            }
            set {
                this["textdoc_fontcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextDocumentsThreadCount {
            get {
                return ((int)(this["TextDocumentsThreadCount"]));
            }
            set {
                this["TextDocumentsThreadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool textDocuments_WordWrap {
            get {
                return ((bool)(this["textDocuments_WordWrap"]));
            }
            set {
                this["textDocuments_WordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TextDocumentAutoSaveTime {
            get {
                return ((int)(this["TextDocumentAutoSaveTime"]));
            }
            set {
                this["TextDocumentAutoSaveTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisualDocumentAutoRender {
            get {
                return ((bool)(this["VisualDocumentAutoRender"]));
            }
            set {
                this["VisualDocumentAutoRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LearnMore {
            get {
                return ((bool)(this["LearnMore"]));
            }
            set {
                this["LearnMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int vdinstance {
            get {
                return ((int)(this["vdinstance"]));
            }
            set {
                this["vdinstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartCount {
            get {
                return ((int)(this["StartCount"]));
            }
            set {
                this["StartCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RECOVERY_ENABLED {
            get {
                return ((bool)(this["RECOVERY_ENABLED"]));
            }
            set {
                this["RECOVERY_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RECOVERY_TIME {
            get {
                return ((int)(this["RECOVERY_TIME"]));
            }
            set {
                this["RECOVERY_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("START_SCREEN")]
        public string OpenWhat {
            get {
                return ((string)(this["OpenWhat"]));
            }
            set {
                this["OpenWhat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PriorityDocument {
            get {
                return ((string)(this["PriorityDocument"]));
            }
            set {
                this["PriorityDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UPDATE_LINKS {
            get {
                return ((bool)(this["UPDATE_LINKS"]));
            }
            set {
                this["UPDATE_LINKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("START")]
        public string UPDATE_LINKS_ON {
            get {
                return ((string)(this["UPDATE_LINKS_ON"]));
            }
            set {
                this["UPDATE_LINKS_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RENDERING_SYSTEM {
            get {
                return ((int)(this["RENDERING_SYSTEM"]));
            }
            set {
                this["RENDERING_SYSTEM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MUIP_CACHING {
            get {
                return ((bool)(this["MUIP_CACHING"]));
            }
            set {
                this["MUIP_CACHING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TEXT_DOCUMENT_SHORTCUTS_ENABLED {
            get {
                return ((bool)(this["TEXT_DOCUMENT_SHORTCUTS_ENABLED"]));
            }
            set {
                this["TEXT_DOCUMENT_SHORTCUTS_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENABLE_EXTERNAL_TOOLS {
            get {
                return ((bool)(this["ENABLE_EXTERNAL_TOOLS"]));
            }
            set {
                this["ENABLE_EXTERNAL_TOOLS"] = value;
            }
        }
    }
}
